# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
variables:
- group: darwin

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      npm run install-app
    displayName: "install"

  - script: |
      npm run build
    displayName: "build"

  - script: |
      npm run test
    displayName: "test"
  - task: CopyFiles@2
    inputs:
      Contents: |
        **/game-frontend/build/**
        **/game-frontend/package.json
        **/game-backend/dist/**
        **/game-backend/package.json
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'